In [233]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.linear_model import LinearRegression

In [234]:
train=pd.read_csv("veriler\datathon\\train.csv")
test=pd.read_csv("veriler\datathon\\testFeatures.csv")

In [235]:
sutunisimler=["tarih","urun","besin","kategori","fiyat","uretimyeri","market","sehir"]
train.columns=sutunisimler

In [236]:
sutunisimler=["id","tarih","urun","besin","kategori","uretimyeri","market","sehir"]
test.columns=sutunisimler

In [237]:
train=train[train["urun"]=="kıyma"]

In [238]:
len(train)

2880

In [239]:
one_hot = pd.get_dummies(test[['uretimyeri','market','sehir']])
test = test.drop(["id",'urun','kategori','uretimyeri','market','sehir','besin'],axis = 1)

test = test.join(one_hot)

In [240]:
one_hot = pd.get_dummies(train[['uretimyeri','market','sehir']])
train = train.drop(['urun','kategori','uretimyeri','market','sehir','besin'],axis = 1)

train = train.join(one_hot)

In [241]:
train["tarih"]=train["tarih"].str.replace("-","").astype(float)
test["tarih"]=test["tarih"].str.replace("-","").astype(float)

In [242]:
train=train.reset_index()

In [243]:
train

,index,tarih,fiyat,uretimyeri_Yurt dışı,uretimyeri_Yurt içi,market_B,market_C,market_M,sehir_A,sehir_B,sehir_C,sehir_D,sehir_E,sehir_F,sehir_G,sehir_H
0,0,20160101.0,33.41,0,1,0,0,1,1,0,0,0,0,0,0,0
1,79,20160101.0,33.71,1,0,0,0,1,1,0,0,0,0,0,0,0
2,158,20160101.0,33.95,0,1,0,1,0,1,0,0,0,0,0,0,0
3,237,20160101.0,32.88,1,0,0,1,0,1,0,0,0,0,0,0,0
4,316,20160101.0,33.53,0,1,1,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,227125,20201201.0,112.71,1,0,0,0,1,0,0,0,0,0,0,0,1
2876,227204,20201201.0,111.89,0,1,0,1,0,0,0,0,0,0,0,0,1
2877,227283,20201201.0,114.62,1,0,0,1,0,0,0,0,0,0,0,0,1
2878,227362,20201201.0,111.36,0,1,1,0,0,0,0,0,0,0,0,0,1
2879,227441,20201201.0,112.91,1,0,1,0,0,0,0,0,0,0,0,0,1

In [244]:
test

,tarih,uretimyeri_Yurt dışı,uretimyeri_Yurt içi,market_B,market_C,market_M,sehir_A,sehir_B,sehir_C,sehir_D,sehir_E,sehir_F,sehir_G,sehir_H
0,20210101.0,0,1,0,0,1,1,0,0,0,0,0,0,0
1,20210101.0,0,1,0,0,1,1,0,0,0,0,0,0,0
2,20210101.0,0,1,0,0,1,1,0,0,0,0,0,0,0
3,20210101.0,0,1,0,0,1,1,0,0,0,0,0,0,0
4,20210101.0,0,1,0,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45499,20211201.0,1,0,1,0,0,0,0,0,0,0,0,0,1
45500,20211201.0,1,0,1,0,0,0,0,0,0,0,0,0,1
45501,20211201.0,1,0,1,0,0,0,0,0,0,0,0,0,1
45502,20211201.0,1,0,1,0,0,0,0,0,0,0,0,0,1
45503,20211201.0,1,0,1,0,0,0,0,0,0,0,0,0,1

In [245]:
y=train.iloc[:,1:2]
x=train.drop(['fiyat'],axis = 1)

In [246]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

In [247]:
regressor=LinearRegression()

In [248]:
regressor.fit(x_train,y_train)

LinearRegression()

In [249]:
testTahminleri=regressor.predict(x_test)

In [253]:
len(testTahminleri)

951

In [251]:
type(y_pred)

numpy.ndarray

In [254]:
tahmin=pd.DataFrame(y_test.values)
testTahminleri= pd.Series(testTahminleri.reshape(951,))
tahminDf=pd.concat([tahmin,testTahminleri],axis=1)
tahminDf.columns=["Gerçek Değer","Test Sonucu"]

In [255]:
tahminDf.head(20)

    Gerçek Değer  Test Sonucu
0     20161201.0   20161201.0
1     20190101.0   20190101.0
2     20200501.0   20200501.0
3     20201001.0   20201001.0
4     20190201.0   20190201.0
5     20190501.0   20190501.0
6     20171201.0   20171201.0
7     20170101.0   20170101.0
8     20190701.0   20190701.0
9     20170301.0   20170301.0
10    20201201.0   20201201.0
11    20171201.0   20171201.0
12    20160301.0   20160301.0
13    20200701.0   20200701.0
14    20160301.0   20160301.0
15    20170301.0   20170301.0
16    20160601.0   20160601.0
17    20170801.0   20170801.0
18    20200401.0   20200401.0
19    20170701.0   20170701.0

In [ ]:
#KAYDETME

In [ ]:
model.save('veriler\datathon\models\\datathon007612')

In [ ]:
# SONUCLARI KAYDETME

In [142]:
testTahminleri=regressor.predict(test)
len(testTahminleri)

45504

In [143]:
testTahminleri= pd.Series(testTahminleri.reshape(45504))

In [40]:
testTahminleri.to_csv('veriler\datathon\sonuclar\\LRtahmin2.csv')

In [43]:
deneme=pd.read_csv('veriler\datathon\sonuclar\\LRtahmin2.csv')

In [44]:
sutunisimler=["id","ürün fiyatı"]
deneme.columns=sutunisimler

ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

In [67]:
deneme.to_csv('veriler\datathon\sonuclar\\datathon007612.csv',index=False)

In [ ]:
#KONTROL

In [68]:
train=pd.read_csv("veriler\datathon\\train.csv")
test=pd.read_csv("veriler\datathon\\testFeatures.csv")

In [69]:
test=test.drop("id",axis=1)

In [71]:
fiyat2021=pd.read_csv("veriler\datathon\sonuclar\\datathon007612.csv")

In [72]:
sutunisimler=["id","ürün fiyatı"]
fiyat2021.columns=sutunisimler
fiyat2021=fiyat2021.drop("id",axis=1)

In [73]:
veri=pd.read_csv("veriler\datathon\\train.csv")

In [74]:
veri2016=train.iloc[:45503,:]
veri2017=train.iloc[45504:91008,:]
veri2018=train.iloc[91008:136512,:]
veri2019=train.iloc[136512:182016,:]
veri2020=train.iloc[182016:,:]

In [75]:
veri2021=pd.concat([fiyat2021,test],axis=1)

In [76]:
veri2021

,ürün fiyatı,tarih,ürün,ürün besin değeri,ürün kategorisi,ürün üretim yeri,market,şehir
0,117.446594,2021-01-01,kıyma,120,et,Yurt içi,M,A
1,38.824978,2021-01-01,tavuk,103,et,Yurt içi,M,A
2,39.103930,2021-01-01,hindi,160,et,Yurt içi,M,A
3,24.652262,2021-01-01,Bakla-kuru,354,sebze ve bakliyat,Yurt içi,M,A
4,41.902905,2021-01-01,Bakla-taze,72,sebze ve bakliyat,Yurt içi,M,A
...,...,...,...,...,...,...,...,...
45499,65.447136,2021-12-01,fındık,110,kuruyemiş,Yurt dışı,B,H
45500,70.385870,2021-12-01,fıstık,115,kuruyemiş,Yurt dışı,B,H
45501,73.389160,2021-12-01,kaju,100,kuruyemiş,Yurt dışı,B,H
45502,68.852080,2021-12-01,badem,110,kuruyemiş,Yurt dışı,B,H
45503,73.649530,2021-12-01,ceviz,120,kuruyemiş,Yurt dışı,B,H

In [77]:
veri2020

,tarih,ürün,ürün besin değeri,ürün kategorisi,ürün fiyatı,ürün üretim yeri,market,şehir
182016,2020-01-01,kıyma,120,et,88.52,Yurt içi,M,A
182017,2020-01-01,tavuk,103,et,30.77,Yurt içi,M,A
182018,2020-01-01,hindi,160,et,32.45,Yurt içi,M,A
182019,2020-01-01,Bakla-kuru,354,sebze ve bakliyat,18.04,Yurt içi,M,A
182020,2020-01-01,Bakla-taze,72,sebze ve bakliyat,32.24,Yurt içi,M,A
...,...,...,...,...,...,...,...,...
227515,2020-12-01,fındık,110,kuruyemiş,51.19,Yurt dışı,B,H
227516,2020-12-01,fıstık,115,kuruyemiş,55.14,Yurt dışı,B,H
227517,2020-12-01,kaju,100,kuruyemiş,58.60,Yurt dışı,B,H
227518,2020-12-01,badem,110,kuruyemiş,51.83,Yurt dışı,B,H
227519,2020-12-01,ceviz,120,kuruyemiş,57.22,Yurt dışı,B,H

In [256]:
testTahminleri

0      20161201.0
1      20190101.0
2      20200501.0
3      20201001.0
4      20190201.0
          ...
946    20170501.0
947    20170401.0
948    20170901.0
949    20190601.0
950    20190401.0
Length: 951, dtype: float64